### PR TITLE
fix broken image link in quick_demo

### PR DESCRIPTION
**Pull request by ulyssebottello**
Hello team 👋

I've just come across a broken image link on your documentation, ([here](https://haystack.deepset.ai/overview/quick-demo)).

I found what would be the right picture on the 'img' folder, and edited the image link.

First PR for me, hope everything will be OK!

### CODE REVIEW

**Comment by TuanaCelik** [comment]
Hey @ulyssebottello thanks for this and good catch! I'll make some changes to fix this in previous versions as well. And now looking at this image I'm worried that it's a bit too big and might make the load time of the page too long. But looking into this too. Maybe we'll create a smaller one instead. Will keep you posted

**Comment by TuanaCelik** [comment]
Hey @ulyssebottello - if you give me push rights to your forked repo I'll commit the required changes. Just uploaded a smaller version of the image to haystack too.

**Comment by ulyssebottello** [comment]
All good @TuanaCelik!

I've just invited you as a collaborator—hmu if I can help you 🙏

**Comment by TuanaCelik** [comment]
All done @ulyssebottello 👍🏽 Merged. Should be fixed soon once the build is complete

**Pull request merged**
