### PR TITLE
283 - Add scroll anchors to h2 and h3 for mdx based pages

### PR DESCRIPTION
**Pull request by fstau**

### CODE REVIEW

**Comment by brandenchan** [comment]
Checked locally and it looks good for Overview, Components, Pipeline Nodes and Guides. @fstau what would it take to extend this to Tutorials and API Reference?

**Comment by brandenchan** [comment]
Fixes #283

**Comment by fstau** [comment]
> Checked locally and it looks good for Overview, Components, Pipeline Nodes and Guides. @fstau what would it take to extend this to Tutorials and API Reference?

@brandenchan There is a separate issue that requires extensive changes to the `GetStaticProps` in those files. I think it would be good to do it in that context.

**Comment by brandenchan** [comment]
Ok understood

**Review by masci — CHANGES_REQUESTED** [review]
The build is failing because we changed the logic. Can you rebase on top of `source` please?

**Pull request closed without merging**
