### PR TITLE
Update document store capabilities

### PR DESCRIPTION
**Pull request by MichelBartels**
This PR updates the document stores component site to include information of filtering capabilities and supported similarity functions.

### CODE REVIEW

**Comment by julian-risch** [comment]
I don't want to BE picky but now that you @brandenchan are polishing the other parts of the documentation, let's also make this nice right away. Could you please review this PR? Should the text maybe read "does not allow using filters with queries"?

**Review by brandenchan — CHANGES_REQUESTED** [review]
Thanks for opening this PR @MichelBartels . These additions are certainly useful. In terms of wording I would go for
"Does not support filters for queries"
"Does not support dot product similarity"

**Comment by MichelBartels** [comment]
Thanks for the feedback. I have now incorporated the changes.

**Review by brandenchan — APPROVED** [review]
LGTM!

**Pull request merged**
